// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: relay/proto/alive.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AliveClient is the client API for Alive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AliveClient interface {
	Hello(ctx context.Context, in *AliveStatus, opts ...grpc.CallOption) (*AliveStatusResp, error)
}

type aliveClient struct {
	cc grpc.ClientConnInterface
}

func NewAliveClient(cc grpc.ClientConnInterface) AliveClient {
	return &aliveClient{cc}
}

func (c *aliveClient) Hello(ctx context.Context, in *AliveStatus, opts ...grpc.CallOption) (*AliveStatusResp, error) {
	out := new(AliveStatusResp)
	err := c.cc.Invoke(ctx, "/v1.Alive/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AliveServer is the server API for Alive service.
// All implementations must embed UnimplementedAliveServer
// for forward compatibility
type AliveServer interface {
	Hello(context.Context, *AliveStatus) (*AliveStatusResp, error)
	mustEmbedUnimplementedAliveServer()
}

// UnimplementedAliveServer must be embedded to have forward compatible implementations.
type UnimplementedAliveServer struct {
}

func (UnimplementedAliveServer) Hello(context.Context, *AliveStatus) (*AliveStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedAliveServer) mustEmbedUnimplementedAliveServer() {}

// UnsafeAliveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AliveServer will
// result in compilation errors.
type UnsafeAliveServer interface {
	mustEmbedUnimplementedAliveServer()
}

func RegisterAliveServer(s grpc.ServiceRegistrar, srv AliveServer) {
	s.RegisterService(&Alive_ServiceDesc, srv)
}

func _Alive_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliveStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliveServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Alive/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliveServer).Hello(ctx, req.(*AliveStatus))
	}
	return interceptor(ctx, in, info, handler)
}

// Alive_ServiceDesc is the grpc.ServiceDesc for Alive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Alive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Alive",
	HandlerType: (*AliveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Alive_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relay/proto/alive.proto",
}
